image: maven:3.8.5-openjdk-17

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar


test:
  stage: test
  script:
    - mvn test
