image: maven:3.8.5-openjdk-17

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp target/*.jar s3://terraform777/